name: Node.js CI

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Try Upgrading Apple Spec
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: update/yarn.lock
      - name: Install
        run: cd update && yarn
      - name: Run
        working-directory: update
        run: yarn start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
